import { getBrowserManager } from "./src/browser.js";
import { capturePageAsSvg } from "./src/svg.js";
import fs from "fs";
const mgr = await getBrowserManager();
const url = "https://webcontentextraction.org/";
const clip = {x:434, y:710, width:1052, height:751};
const page1 = await mgr.newPage({backend: mgr.config.defaultBackend});
await page1.goto(url, {waitUntil: mgr.config.navWaitUntil, timeout: mgr.config.browserOpTimeoutMs});
await page1.waitForFunction(()=>document.readyState==="complete",{timeout:10000}).catch(()=>{});
await new Promise(r=>setTimeout(r,800));
const buf1 = await page1.screenshot({clip, type:"png"});
fs.writeFileSync("/tmp/leaderboard-original.png", buf1);
console.log("original clip", buf1.length);
const cap = await capturePageAsSvg(page1, {elementLimit:500, fullPage:true, hybrid:false});
await page1.close();
const page2 = await mgr.newPage({backend: mgr.config.defaultBackend});
const dataUrl = "data:image/svg+xml;base64," + Buffer.from(cap.svg).toString("base64");
await page2.goto(dataUrl, {waitUntil:"load", timeout:10000});
await page2.setViewport({width:1920, height:8620});
await new Promise(r=>setTimeout(r,500));
const buf2 = await page2.screenshot({clip, type:"png"});
fs.writeFileSync("/tmp/leaderboard-svg.png", buf2);
console.log("svg clip", buf2.length);
await page2.close();
