export const CONFIG_SCHEMA = [
  { key: "BROWSER_BACKEND", category: "backend", type: "enum", values: ["cloakbrowser", "lightpanda", "chromium"], fallback: "cloakbrowser", applies: "recreate", description: "Primary browser backend for page fetch/screenshot." },
  { key: "DEVTOOLS_BROWSER_BACKEND", category: "backend", type: "enum", values: ["cloakbrowser", "lightpanda", "chromium"], fallback: "cloakbrowser", applies: "recreate", description: "Backend used by the devtools testing tools." },
  { key: "HEADLESS", category: "backend", type: "boolean", fallback: true, applies: "recreate", description: "Run browsers without a UI. Toggled automatically by the VNC control." },
  { key: "CHROME_PATH", category: "backend", type: "string", fallback: "/usr/bin/chromium", applies: "recreate", description: "Path to the Chromium executable." },
  { key: "CHROME_USER_DATA_DIR", category: "backend", type: "string", fallback: "/data/chrome", applies: "recreate", description: "Persistent Chrome profile directory." },
  { key: "CHROME_PROFILE_DIR", category: "backend", type: "string", fallback: "Default", applies: "recreate", description: "Chrome profile folder name." },
  { key: "LIGHTPANDA_PATH", category: "backend", type: "string", fallback: "auto-detect", applies: "recreate", description: "Path to the lightpanda binary." },
  { key: "LIGHTPANDA_PORT", category: "backend", type: "number", fallback: 9222, applies: "recreate", description: "CDP port for lightpanda." },
  { key: "CLOAKBROWSER_BINARY_PATH", category: "backend", type: "string", fallback: "auto-detect", applies: "recreate", description: "Path to the cloakbrowser chrome binary." },
  { key: "PRELAUNCH_BROWSER", category: "backend", type: "boolean", fallback: true, applies: "recreate", description: "Pre-launch browser on server start." },
  { key: "STARTUP_URL", category: "backend", type: "string", fallback: "about:blank", applies: "recreate", description: "URL opened in the browser on launch." },
  { key: "BROWSER_USER_AGENT", category: "backend", type: "string", fallback: "Chromium UA", applies: "recreate", description: "User agent string used by the browsers." },

  { key: "SEARCH_ROUTE_WARMUP_ENGINES", category: "search", type: "engines", fallback: ["duckduckgo_api", "google_cb", "google_lp", "bing_lp", "duckduckgo_cb", "bing_cb"], applies: "hot", description: "Search routes prewarmed on start (star = primary)." },
  { key: "SEARCH_FALLBACK", category: "search", type: "engines", fallback: null, applies: "hot", description: "Fallback engine order when primary routes fail." },
  { key: "SEARCH_ROUTE_CIRCUIT_OPEN_MS", category: "search", type: "number", fallback: 300000, applies: "hot", description: "Route cooldown after failure (ms)." },
  { key: "SEARCH_KEEP_MIN_WORKING_WINDOWS", category: "search", type: "integer", min: 0, fallback: 2, applies: "hot", description: "Min warm windows kept open per engine." },
  { key: "SEARCH_MAX_WORKING_WINDOWS", category: "search", type: "integer", fallback: 10, applies: "hot", description: "Max concurrent windows per engine." },
  { key: "OPEN_PAGE_MAX_PARALLEL", category: "search", type: "integer", fallback: 6, applies: "hot", description: "Max parallel open_page operations." },
  { key: "MAX_CONCURRENT_PAGE_OPS", category: "search", type: "integer", fallback: 30, applies: "hot", description: "Global max concurrent page operations." },
  { key: "HUMAN_TYPING_DELAY", category: "search", type: "integer", min: 0, fallback: 15, applies: "hot", description: "Delay per character typed (ms)." },
  { key: "STABILIZE_STRATEGY", category: "search", type: "enum", values: ["network_idle", "content_idle", "mutation", "none"], fallback: "network_idle", applies: "hot", description: "Page stabilization strategy." },

  { key: "BROWSER_OP_TIMEOUT_MS", category: "ops", type: "number", fallback: 60000, applies: "hot", description: "Timeout for browser operations (ms)." },
  { key: "NAV_WAIT_UNTIL", category: "ops", type: "enum", values: ["load", "domcontentloaded", "networkidle0", "networkidle2"], fallback: "domcontentloaded", applies: "hot", description: "Navigation wait strategy." },
  { key: "WEB_FETCH_MAX_CHARS", category: "ops", type: "number", fallback: 90000, applies: "hot", description: "Default max characters per fetched page." },
  { key: "DEBUG", category: "ops", type: "boolean", fallback: false, applies: "hot", description: "Per-step benchmark timing logs." },
  { key: "LOG_TOOL_ERRORS", category: "ops", type: "boolean", fallback: true, applies: "hot", description: "Log tool errors to logs/tool-errors.log." },
  { key: "DISABLE_TOOLS", category: "ops", type: "toolList", fallback: [], applies: "hot", description: "MCP tools to hide/reject (comma-separated)." },
  { key: "DOMAIN_HINTS_PATH", category: "ops", type: "string", fallback: "domain-hints.json", applies: "recreate", description: "Path to extraction hints file." },
  { key: "ENABLE_HANG_RESTART", category: "ops", type: "boolean", fallback: false, applies: "hot", description: "Exit process on hung top-level ops so Docker restarts." },
  { key: "HANG_RESTART_TIMEOUT_MS", category: "ops", type: "number", fallback: 120000, applies: "hot", description: "Hang threshold for forced restart (ms)." },

  { key: "ENABLE_WEB_CONSOLE", category: "console", type: "boolean", fallback: true, applies: "recreate", description: "Serve the web console at /console." },
  { key: "ENABLE_HTTP_HEALTH", category: "console", type: "boolean", fallback: false, applies: "recreate", description: "Serve /health and /stats." },
  { key: "ENABLE_HTTP_MCP", category: "console", type: "boolean", fallback: false, applies: "recreate", description: "Serve the MCP endpoint at /mcp." },
  { key: "MCP_ALLOW_UNAUTHENTICATED", category: "console", type: "boolean", fallback: true, applies: "hot", description: "Allow /mcp requests without an API key." },
  { key: "ENABLE_STDIO_MCP", category: "console", type: "boolean", fallback: true, applies: "recreate", description: "Run MCP over stdio." },
  { key: "ENABLE_DEVTOOLS_MCP", category: "console", type: "boolean", fallback: false, applies: "recreate", description: "Expose devtools browser tools via MCP." },
  { key: "MCP_API_PORT", category: "console", type: "number", fallback: 3000, applies: "recreate", description: "Port the HTTP server listens on." },
  { key: "MCP_API_HOST", category: "console", type: "string", fallback: "http://localhost", applies: "recreate", description: "Host base shown in logs." },
  { key: "ENABLE_SCREENSHOT_DOWNLOAD_LINK", category: "console", type: "boolean", fallback: false, applies: "recreate", description: "Serve screenshot files at /download/." },
  { key: "ENABLE_SCREENSHOT_PATH", category: "console", type: "string", fallback: "", applies: "recreate", description: "Where screenshot files are stored (empty = in-memory)." },

  { key: "ENABLE_VNC", category: "vnc", type: "boolean", fallback: false, applies: "hot", description: "VNC mode. Toggled automatically by the console VNC control." },
  { key: "VNC_PORT", category: "vnc", type: "number", fallback: 5900, applies: "recreate", description: "x11vnc port." },
  { key: "NOVNC_PORT", category: "vnc", type: "number", fallback: 7900, applies: "recreate", description: "noVNC web port (published to host)." }
];
