import { DEFAULT_SEARCH_ENABLED_ENGINES } from "./config.js";

export const CONFIG_SCHEMA = [
  { key: "BROWSERS", category: "backend", type: "json", fallback: '[{"name":"chromium","role":[]},{"name":"cloakbrowser","role":["default","search","fetch","screenshot","devtools"],"cdpUrl":"http://cloak-browser:9222"}]', applies: "hot", description: 'JSON array of browser entries. Each entry: {name, role:[], cdpUrl?, prompt?}. Roles: "default" (everything), "search" (web_search), "fetch" (web_fetch), "screenshot" (web_page_screenshot/ascii/svg), "devtools" (browser_* tools). Chromium is always present (no cdpUrl); an empty role array makes it a fallback/backup only. Add-ons (CloakBrowser, etc.) must provide a cdpUrl (ws:// endpoint or http:// CDP server). Optional prompt = agent-facing instruction shown in list_browsers (add-ons only).' },
  { key: "HEADLESS", category: "backend", type: "boolean", fallback: true, applies: "hot", description: "Run browsers without a UI. Toggled automatically by the VNC control." },
  { key: "CHROME_PATH", category: "backend", type: "string", fallback: "/usr/bin/chromium", applies: "hot", description: "Path to the Chromium executable." },
  { key: "CHROME_USER_DATA_DIR", category: "backend", type: "string", fallback: "/data/chrome", applies: "hot", description: "Persistent Chrome profile directory." },
  { key: "CHROME_PROFILE_DIR", category: "backend", type: "string", fallback: "Default", applies: "hot", description: "Chrome profile folder name." },
  { key: "PRELAUNCH_BROWSER", category: "backend", type: "boolean", fallback: true, applies: "hot", description: "Pre-launch browser on server start." },
  { key: "STARTUP_URL", category: "backend", type: "string", fallback: "about:blank", applies: "hot", description: "URL opened in the browser on launch." },
  { key: "BROWSER_USER_AGENT", category: "backend", type: "string", fallback: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36", applies: "hot", description: "User agent string used by the browsers." },

  { key: "SEARCH_ROUTE_WARMUP_ENGINES", category: "search", type: "engines", fallback: ["brave", "duckduckgo_api", "duckduckgo"], applies: "hot", description: "Browser routes prewarmed on start." },
  { key: "SEARCH_ENABLED_ENGINES", category: "search", type: "engines", fallback: DEFAULT_SEARCH_ENABLED_ENGINES, applies: "hot", description: "Search routes eligible for automatic select_best scheduling." },
  { key: "SEARCH_ROUTE_CIRCUIT_OPEN_MS", category: "search", type: "number", fallback: 300000, applies: "hot", description: "Route cooldown after failure (ms)." },
  { key: "EXA_API_KEY", category: "search", type: "string", fallback: "", applies: "hot", description: "API key for exa_api search (https://dashboard.exa.ai/api-keys). When empty, exa_api is disabled." },
  { key: "LINKUP_API_KEY", category: "search", type: "string", fallback: "", applies: "hot", description: "API key for linkup_api search (https://app.linkup.so/api-keys). When empty, linkup_api is disabled." },
  { key: "TAVILY_API_KEY", category: "search", type: "string", fallback: "", applies: "hot", description: "API key for tavily_api search (https://app.tavily.com/). When empty, tavily_api is disabled." },
  { key: "FIRECRAWL_API_KEY", category: "search", type: "string", fallback: "", applies: "hot", description: "API key for firecrawl_api search (https://www.firecrawl.dev/app/api-keys). When empty, firecrawl_api is disabled." },
  { key: "SEARCH_KEEP_MIN_WORKING_WINDOWS", category: "search", type: "integer", min: 0, fallback: 2, applies: "hot", description: "Min warm windows per route pool; the shared pool is capped at one." },
  { key: "SEARCH_MAX_WORKING_WINDOWS", category: "search", type: "integer", fallback: 10, applies: "hot", description: "Max concurrent windows per engine." },
  { key: "SEARCH_QUEUE_MIN_INTERVAL_MS", category: "search", type: "number", fallback: 30000, applies: "hot", description: "Baseline minimum gap between automatic calls to one engine (ms)." },
  { key: "SEARCH_QUEUE_MAX_INTERVAL_MS", category: "search", type: "number", fallback: 1800000, applies: "hot", description: "Cap for learned engine backoff (ms)." },
  { key: "SEARCH_QUEUE_ESCALATION_FACTOR", category: "search", type: "number", fallback: 2, applies: "hot", description: "Backoff multiplier after a failure." },
{ key: "SEARCH_QUEUE_ERROR_GAP_PERCENTILE", category: "search", type: "number", min: 0, fallback: 0.75, applies: "hot", description: "Failure-gap percentile used to learn safe retry intervals." },
  { key: "SEARCH_QUEUE_ERROR_GAP_SAFETY", category: "search", type: "number", min: 0, fallback: 1.25, applies: "hot", description: "Safety multiplier applied to learned failure gaps." },
  { key: "SEARCH_QUEUE_DECAY_PER_SUCCESS", category: "search", type: "number", min: 0, fallback: 0.75, applies: "hot", description: "Backoff multiplier after each successful recovery." },
  { key: "SEARCH_QUEUE_PROFILE_PATH", category: "search", type: "string", fallback: ".cache/search-engine-profiles.json", applies: "hot", description: "Persisted scheduler profile path." },
  { key: "SEARCH_QUEUE_W_SUCCESS", category: "search", type: "number", min: 0, fallback: 0.45, applies: "hot", description: "Scheduler score weight for success rate." },
  { key: "SEARCH_QUEUE_W_RESULTS", category: "search", type: "number", min: 0, fallback: 0.15, applies: "hot", description: "Scheduler score weight for results per attempt." },
  { key: "SEARCH_QUEUE_W_STABILITY", category: "search", type: "number", min: 0, fallback: 0.25, applies: "hot", description: "Scheduler score weight for recent stability." },
  { key: "SEARCH_QUEUE_W_RECENCY", category: "search", type: "number", min: 0, fallback: 0.1, applies: "hot", description: "Scheduler score weight for recent-failure penalty." },
  { key: "SEARCH_QUEUE_W_RECOVERY", category: "search", type: "number", min: 0, fallback: 0.05, applies: "hot", description: "Scheduler score weight for recovery successes." },
  { key: "SEARCH_QUEUE_W_LATENCY", category: "search", type: "number", min: 0, fallback: 0.2, applies: "hot", description: "Scheduler score weight for observed response latency." },
  { key: "OPEN_PAGE_MAX_PARALLEL", category: "search", type: "integer", fallback: 6, applies: "hot", description: "Max parallel open_page operations." },
  { key: "MAX_CONCURRENT_PAGE_OPS", category: "search", type: "integer", fallback: 30, applies: "hot", description: "Global max concurrent page operations." },
  { key: "HUMAN_TYPING_DELAY", category: "search", type: "integer", min: 0, fallback: 15, applies: "hot", description: "Delay per character typed (ms)." },

  { key: "BROWSER_OP_TIMEOUT_MS", category: "ops", type: "number", fallback: 60000, applies: "hot", description: "Timeout for browser operations (ms)." },
  { key: "NAV_WAIT_UNTIL", category: "ops", type: "enum", values: ["load", "domcontentloaded", "networkidle0", "networkidle2"], fallback: "domcontentloaded", applies: "hot", description: "Navigation wait strategy." },
  { key: "WEB_FETCH_MAX_CHARS", category: "ops", type: "number", fallback: 90000, applies: "hot", description: "Default max characters per fetched page." },
  { key: "LINK_REFS", category: "ops", type: "boolean", fallback: true, applies: "hot", description: "Rewrite extracted links to [text](ref_id) format for web_page_links resolution." },
  { key: "DEBUG", category: "ops", type: "boolean", fallback: false, applies: "hot", description: "Per-step benchmark timing logs." },
  { key: "LOG_TOOL_ERRORS", category: "ops", type: "boolean", fallback: true, applies: "hot", description: "Log tool errors to logs/tool-errors.log." },
  { key: "DISABLE_TOOLS", category: "ops", type: "toolList", fallback: [], applies: "hot", description: "MCP tools to hide/reject (comma-separated)." },
  { key: "DOMAIN_HINTS_PATH", category: "ops", type: "string", fallback: "domain-hints.json", applies: "hot", description: "Path to extraction hints file." },
  { key: "ENABLE_HANG_RESTART", category: "ops", type: "boolean", fallback: false, applies: "hot", description: "Exit process on hung top-level ops so Docker restarts." },
  { key: "HANG_RESTART_TIMEOUT_MS", category: "ops", type: "number", fallback: 120000, applies: "hot", description: "Hang threshold for forced restart (ms)." },

  { key: "ENABLE_WEB_CONSOLE", category: "console", type: "boolean", fallback: true, applies: "hot", description: "Serve the web console at /console." },
  { key: "ENABLE_HTTP_HEALTH", category: "console", type: "boolean", fallback: false, applies: "hot", description: "Serve /health and /stats." },
  { key: "ENABLE_HTTP_MCP", category: "console", type: "boolean", fallback: false, applies: "hot", description: "Serve the MCP endpoint at /mcp." },
  { key: "MCP_ALLOW_UNAUTHENTICATED", category: "console", type: "boolean", fallback: true, applies: "hot", description: "Allow /mcp requests without an API key." },
  { key: "ENABLE_CDP_SHARING", category: "console", type: "boolean", fallback: true, applies: "hot", description: "Expose configured browsers as authenticated CDP endpoints at /cdp/<browser>?key= (plan 55). CDP always requires a valid API key." },
  { key: "MCP_PUBLIC_URL", category: "console", type: "string", fallback: "", applies: "hot", description: "Public base URL advertised in CDP connect URLs (e.g. https://navigator.example.com). Empty = derive from MCP_API_HOST/MCP_API_PORT." },
  { key: "ENABLE_STDIO_MCP", category: "console", type: "boolean", fallback: true, applies: "hot", description: "Run MCP over stdio." },
  { key: "ENABLE_DEVTOOLS_MCP", category: "console", type: "boolean", fallback: false, applies: "hot", description: "Expose devtools browser tools via MCP." },
  { key: "MCP_API_PORT", category: "console", type: "number", fallback: 1994, applies: "hot", description: "Port the HTTP server listens on." },
  { key: "MCP_API_HOST", category: "console", type: "string", fallback: "http://localhost", applies: "hot", description: "Host base shown in logs." },
  { key: "ENABLE_SCREENSHOT_DOWNLOAD_LINK", category: "console", type: "boolean", fallback: false, applies: "hot", description: "Serve screenshot files at /download/." },
  { key: "ENABLE_SCREENSHOT_PATH", category: "console", type: "string", fallback: "", applies: "hot", description: "Where screenshot files are stored (empty = in-memory)." },

  { key: "ENABLE_VNC", category: "vnc", type: "boolean", fallback: false, applies: "hot", description: "VNC mode. Toggled automatically by the console VNC control." },
  { key: "VNC_PORT", category: "vnc", type: "number", fallback: 1995, applies: "hot", description: "x11vnc port." },
  { key: "NOVNC_PORT", category: "vnc", type: "number", fallback: 1996, applies: "hot", description: "noVNC web port (published to host)." },

  { key: "POST_PROCESSOR_MODELS", category: "extractor", type: "string", fallback: "[]", applies: "hot", description: 'JSON array of post-processor models, e.g. [{"id":"reader_lm","label":"reader-lm-0.5b","model":"jinaai/reader-lm-0.5b","baseUrl":"http://host.docker.internal:8000/v1"}]. Each id becomes an "AI Model" option in the extractor/post-processor dropdowns. Each entry accepts an optional kind: "chat" (default; OpenAI-compatible /chat/completions), "mineru" (POST {html} to baseUrl/extract), or "api" (custom endpoint with body/outputField). Per-entry timeoutMs/maxInputChars/maxTokens override defaults. reader-lm weights are CC-BY-NC-4.0 non-commercial; the MinerU-HTML model carries the Tencent Hunyuan Community License. (Legacy names: AI_EXTRACTOR_MODELS, READER_LM_MODELS.)' }
];
